language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
  - composer install
script: 
  - mkdir -p build/logs
  - bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
  - bin/coveralls
